### ISSUE TITLE
Consider stop using automerge here

### ISSUE THREAD

**Issue by ccordoba12** [conda-forge/sphinx-feedstock#117]
Sphinx is a dependency used by a lot of projects in the Python ecosystem, so auto-merging can have a huge negative impact and add more work to other Conda-forge maintainers, when important changes or new dependencies are introduced in future versions.

A recent example is Sphinx 4.4.0, which introduced a new dependency on `importlib-metadata`. This was omitted in https://github.com/conda-forge/sphinx-feedstock/pull/116, which forced other maintainers to step up and submit followup PRs to fix it:

* https://github.com/conda-forge/sphinx-feedstock/pull/116
* https://github.com/conda-forge/admin-requests/pull/378

Pinging @conda-forge/sphinx about this.

**Comment by chohner** [comment]
This just happened again in the `v5.0.0` release (with less breakage), due to the new release supporting `docutils>=0.14,<0.19`.

**Comment by chohner** [comment]
fixed in 5d4ad53949bf864b4747186b9b4e1ad3c80de7fc

**Comment by ccordoba12** [comment]
Thanks @chohner!
