### ISSUE TITLE
Sphinx 6 drops support for py 3.7, but still pins python>=3.7

### ISSUE THREAD

**Issue by FaustinCarter** [conda-forge/sphinx-feedstock#137]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Sphinx 6.0 drops support for python 3.7 (https://www.sphinx-doc.org/en/master/changes.html#release-6-0-0-released-dec-29-2022). Hoever, the meta.yaml in this recipe is still pinning to `python >= 3.7` rather than `python >= 3.8`. This is causing import problems in python 3.7 environments that update sphinx and accidentally get v6 (because the pinning here is wrong).

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by jakirkham** [comment]
Would also suggest making a repodata patch ( analogous to PR https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/355 )

**Comment by FaustinCarter** [comment]
> Would also suggest making a repodata patch ( analogous to PR [conda-forge/conda-forge-repodata-patches-feedstock#355](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/355) )

Link to PR for this: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/382
