### ISSUE TITLE
Windows Python 2.7 uploads failing

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/sphinx-feedstock#16]
Seems we are running into issue ( https://github.com/conda-forge/conda-forge-build-setup-feedstock/issues/60 ) on `master`. This is blocking Windows Python 2.7 uploads.

**Comment by chohner** [comment]
Yea. Another note: seems like appveyor is using `conda-build 2.1.6` rather than newest `2.1.7`. But that still did work for the PR.

**Comment by jakirkham** [comment]
I think everything is still using 2.1.6, right? Or am I missing something?

**Comment by jakirkham** [comment]
In any event, the issue is in the upload script somewhere. So the PR wouldn't have given us any indication this was going to happen. I'm not entirely clear on why this is happening. That said, it is not unique to this feedstock.

**Comment by chohner** [comment]
With `conda-build 2.1.4` I think we are back to the initial error:
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 48: ordinal not in range(128)`

**Comment by jakirkham** [comment]
Yep, it's a lose-lose situation right now. We will have to wait and see how issue ( https://github.com/conda/conda-build/issues/1853 ) gets sorted.

**Comment by chohner** [comment]
So this is now fixed? I submitted the PR for the newest rerender (https://github.com/conda-forge/sphinx-feedstock/pull/18) but on appveyor py27 at least, `conda-build` is still on 2.1.4. Should I manually update?

**Comment by jakirkham** [comment]
Let me ask others about unpinning this. ( https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/64 )

**Comment by jakirkham** [comment]
Let's see if PR ( https://github.com/conda-forge/sphinx-feedstock/pull/18 ) passes. If so, we should be back in business.
